"""Nonlinear constrained MPC for the analytical planar arm.

The controller uses direct shooting: the decision variables are the torque
commands over a short horizon and the exact analytical RK4 plant is rolled
forward inside the objective.  SciPy/SLSQP handles box constraints on torque
and nonlinear state constraints on joint position and velocity.

This is intentionally a reference-quality controller rather than a fast
real-time solver.  Later robot backends can replace the optimiser while
keeping the same cost/constraint semantics.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from scipy.optimize import Bounds, minimize

from sarrl.dynamics import PlanarArm


@dataclass(frozen=True)
class MPCConfig:
    horizon: int = 8
    dt: float = 0.02
    q_weight: tuple[float, float] = (16.0, 16.0)
    qd_weight: tuple[float, float] = (1.5, 1.5)
    torque_weight: tuple[float, float] = (0.002, 0.002)
    terminal_multiplier: float = 5.0
    torque_limit: tuple[float, float] = (40.0, 40.0)
    joint_limit: tuple[float, float] = (-3.05, 3.05)
    velocity_limit: float = 7.0
    max_iterations: int = 80
    ftol: float = 1e-7

    def validate(self) -> None:
        if self.horizon <= 0 or not np.isfinite(self.dt) or self.dt <= 0.0:
            raise ValueError("horizon and dt must be positive")
        if self.terminal_multiplier <= 0.0 or self.max_iterations <= 0 or self.ftol <= 0.0:
            raise ValueError("terminal multiplier, iterations and ftol must be positive")
        if self.joint_limit[0] >= self.joint_limit[1] or self.velocity_limit <= 0.0:
            raise ValueError("invalid state limits")
        for values in (self.q_weight, self.qd_weight, self.torque_weight, self.torque_limit):
            if len(values) != 2 or not all(np.isfinite(v) and v > 0.0 for v in values):
                raise ValueError("MPC weights and torque limits must be positive finite pairs")


@dataclass(frozen=True)
class MPCResult:
    torque: np.ndarray
    sequence: np.ndarray
    success: bool
    status: int
    iterations: int
    cost: float
    min_constraint_margin: float


class NonlinearMPC:
    """Short-horizon constrained nonlinear MPC with warm starting."""

    def __init__(self, model: PlanarArm, config: MPCConfig | None = None):
        self.model = model
        self.config = config or MPCConfig()
        self.config.validate()
        self._warm_start = np.zeros((self.config.horizon, 2), dtype=np.float64)

    @staticmethod
    def _state4(state) -> np.ndarray:
        state = np.asarray(state, dtype=np.float64)
        if state.shape != (4,) or not np.all(np.isfinite(state)):
            raise ValueError("state must be a finite vector of shape (4,)")
        return state

    @staticmethod
    def _q2(q_des) -> np.ndarray:
        q_des = np.asarray(q_des, dtype=np.float64)
        if q_des.shape != (2,) or not np.all(np.isfinite(q_des)):
            raise ValueError("q_des must be a finite vector of shape (2,)")
        return q_des

    def rollout(self, state, sequence) -> np.ndarray:
        """Return states x_1..x_H generated by one torque sequence."""
        x = self._state4(state).copy()
        u = np.asarray(sequence, dtype=np.float64)
        if u.shape != (self.config.horizon, 2) or not np.all(np.isfinite(u)):
            raise ValueError("sequence must have shape (horizon, 2) and be finite")
        states = np.zeros((self.config.horizon, 4), dtype=np.float64)
        for k in range(self.config.horizon):
            x = self.model.step_rk4(x, u[k], self.config.dt)
            states[k] = x
        return states

    def objective(self, flat_sequence, state, q_des) -> float:
        sequence = np.asarray(flat_sequence, dtype=np.float64).reshape(self.config.horizon, 2)
        states = self.rollout(state, sequence)
        target = self._q2(q_des)
        qw = np.asarray(self.config.q_weight)
        vw = np.asarray(self.config.qd_weight)
        uw = np.asarray(self.config.torque_weight)
        cost = 0.0
        for k, x in enumerate(states):
            q_err = np.arctan2(np.sin(target - x[:2]), np.cos(target - x[:2]))
            mult = self.config.terminal_multiplier if k == self.config.horizon - 1 else 1.0
            cost += mult * float(np.sum(qw * q_err * q_err))
            cost += mult * float(np.sum(vw * x[2:] * x[2:]))
            cost += float(np.sum(uw * sequence[k] * sequence[k]))
        return cost

    def constraint_margins(self, flat_sequence, state) -> np.ndarray:
        """Positive values mean every predicted state satisfies its hard limits."""
        sequence = np.asarray(flat_sequence, dtype=np.float64).reshape(self.config.horizon, 2)
        states = self.rollout(state, sequence)
        qlo, qhi = self.config.joint_limit
        vmax = self.config.velocity_limit
        margins = []
        for x in states:
            margins.extend(x[:2] - qlo)
            margins.extend(qhi - x[:2])
            margins.extend(x[2:] + vmax)
            margins.extend(vmax - x[2:])
        return np.asarray(margins, dtype=np.float64)

    def _initial_guess(self, state, q_des) -> np.ndarray:
        # Use the warm start when available.  On the first solve, fill the
        # sequence with exact gravity compensation; this is substantially
        # closer to a feasible useful trajectory than zero torque.
        if np.any(self._warm_start):
            return self._warm_start.copy()
        gravity = self.model.inverse_dynamics(
            self._q2(q_des), np.zeros(2), np.zeros(2), include_friction=True
        )
        limit = np.asarray(self.config.torque_limit)
        return np.tile(np.clip(gravity, -limit, limit), (self.config.horizon, 1))

    def command(self, state, q_des) -> MPCResult:
        state = self._state4(state)
        q_des = self._q2(q_des)
        limit = np.asarray(self.config.torque_limit, dtype=np.float64)
        guess = self._initial_guess(state, q_des)
        bounds = Bounds(
            np.tile(-limit, self.config.horizon),
            np.tile(limit, self.config.horizon),
        )
        constraints = {
            "type": "ineq",
            "fun": lambda z: self.constraint_margins(z, state),
        }
        opt = minimize(
            self.objective,
            guess.ravel(),
            args=(state, q_des),
            method="SLSQP",
            bounds=bounds,
            constraints=(constraints,),
            options={
                "maxiter": self.config.max_iterations,
                "ftol": self.config.ftol,
                "disp": False,
            },
        )
        sequence = np.asarray(opt.x, dtype=np.float64).reshape(self.config.horizon, 2)
        margins = self.constraint_margins(sequence.ravel(), state)
        min_margin = float(np.min(margins))
        success = bool(opt.success and np.isfinite(opt.fun) and min_margin >= -2e-6)

        # Shift the best sequence for the next call, regardless of convergence:
        # SLSQP's final feasible iterate is often a much better warm start.
        self._warm_start[:-1] = sequence[1:]
        self._warm_start[-1] = sequence[-1]
        torque = np.clip(sequence[0], -limit, limit)
        return MPCResult(
            torque=torque,
            sequence=sequence,
            success=success,
            status=int(opt.status),
            iterations=int(getattr(opt, "nit", 0)),
            cost=float(opt.fun),
            min_constraint_margin=min_margin,
        )

    def reset(self) -> None:
        self._warm_start.fill(0.0)
